[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".config/nvim"]
  type = "archive"
  url = "https://github.com/dhruvinsh/nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 1
[".emacs.d"]
  type = "archive"
  url = "https://github.com/hlissner/doom-emacs/archive/develop.tar.gz"
  exact = true
  stripComponents = 1
[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".nvm"]
  type = "archive"
  url = "https://github.com/nvm-sh/nvm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".pyenv"]
  type = "archive"
  url = "https://github.com/pyenv/pyenv/archive/master.tar.gz"
  exact = true
  stripComponents = 1
