# chezmoixternal -*- mode: toml -*-
# vim: set filetype=yaml

ageVersion: "1.1.1"
batVersion: "0.22.1"
emacsVersion: "28.2"
fdVersion: "8.7.0"
fzfVersion: "0.38.0"
ghVersion: "2.23.0"
goVersion: "1.19.2"
lazygitVersion: "0.37.0"
logseqVersion: "0.8.17"
neovideVersion: "0.10.3"
neovimVersion: "0.8.3"
pythonVersion: "3.11.2"
ripgrepVersion: "13.0.0"
seleneVersion: "0.24.0"
shfmtVersion: "3.6.0"
starshipVersion: "1.13.0"
styluaVersion: "0.16.1"
syncthingVersion: "1.23.1"
tealdeerVersion: "1.6.1"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion: "0.13.0"
