# chezmoixternal -*- mode: toml -*-
# vim: set filetype=yaml

ageVersion: "1.1.1"
batVersion: "0.23.0"
emacsVersion: "28.2"
f3dVersion: "1.3.1"
fdVersion: "8.7.0"
freecadVersion: "0.20.2-2022-12-27"
fzfVersion: "0.38.0"
ghVersion: "2.25.1"
goVersion: "1.19.2"
lazygitVersion: "0.37.0"
logseqVersion: "0.9.1"
neovideVersion: "0.10.3"
neovimVersion: "0.9.0"
nextcloudVersion: "3.7.4"
openscadVersion: "2021.01"
pythonVersion: "3.11.2"
ripgrepVersion: "13.0.0"
rustfmtVersion: "1.5.1"
seleneVersion: "0.25.0"
shfmtVersion: "3.6.0"
starshipVersion: "1.13.1"
styluaVersion: "0.17.1"
syncthingVersion: "1.23.4"
tealdeerVersion: "1.6.1"
weztermVersion: "20230320-124340-559cb7b0"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion: "0.13.0"
