# chezmoixternal -*- mode: yaml -*-
# vim: set filetype=yaml

# prettier-ignore
ageVersion       : "1.1.1"
batVersion       : "0.24.0"
f3dVersion       : "2.2.1"
fdVersion        : "8.7.1"
freecadVersion   : "0.20.2-2022-12-27"
fzfVersion       : "0.44.0"
ghVersion        : "2.39.1"
glowVersion      : "1.5.1"
helixVersion     : "23.10"
lazydockerVersion: "0.23.1"
lazygitVersion   : "0.40.2"
neovideVersion   : "0.11.2"
nerdfontVersion  : "3.1.0"
nextcloudVersion : "3.10.1"
openscadVersion  : "2021.01"
pythonVersion    : "3.11.4"
ripgrepVersion   : "14.0.3"
rustfmtVersion   : "1.6.0"
sniffnetVersion  : "1.2.2"
syncthingVersion : "1.26.1"
tealdeerVersion  : "1.6.1"
zoxideVersion    : "0.9.2"
