# chezmoixternal -*- mode: toml -*-
# vim: set filetype=yaml

ageVersion: "1.0.0"
batVersion: "0.22.1"
emacsVersion: "28.2"
fdVersion: "8.5.3"
fzfVersion: "0.35.1"
ghVersion: "2.20.2"
goVersion: "1.19.2"
lazygitVersion: "0.36.0"
neovideVersion: "0.10.3"
neovimVersion: "0.8.1"
pythonVersion: "3.10.8"
ripgrepVersion: "13.0.0"
seleneVersion: "0.22.0"
shfmtVersion: "3.5.1"
starshipVersion: "1.11.0"
styluaVersion: "0.15.2"
syncthingVersion: "1.22.1"
tealdeerVersion: "1.6.1"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion: "0.13.0"
