# chezmoixternal -*- mode: yaml -*-
# vim: set ft=yaml

# config that applies to windows and linux
.config/wezterm:
  type: git-repo
  url: "https://github.com/dhruvinsh/wezterm-config.git"
  pull:
    args:
      - "--ff-only"

{{ $nvimPath := "" }}
{{ if eq .chezmoi.os "windows" }}
{{   $nvimPath = "AppData/Local/nvim" }}
{{ else if eq .chezmoi.os "linux" }}
{{   $nvimPath = ".config/nvim" }}
{{ end }}

{{ $nvimPath }}:
  type: git-repo
  url: "https://github.com/dhruvinsh/nvim.git"
  pull:
    args:
      - "--ff-only"

# work on linux based system only
{{ if eq .chezmoi.os "linux" }}

{{ if .isDesktop -}}
.config/kitty/kitty-themes:
  type: archive
  url: "https://github.com/dhruvinsh/kitty-themes/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{ end -}}

.local/bin/lazygit:
  type: file
  url: >-
    https://github.com/jesseduffield/lazygit/releases/download/v{{ .lazygitVersion }}/lazygit_{{.lazygitVersion }}_Linux_x86_64.tar.gz
  executable: true
  filter:
    command: tar
    args:
      - "--extract"
      - "--file"
      - /dev/stdin
      - "--gzip"
      - "--to-stdout"
      - lazygit

.local/bin/lazydocker:
  type: file
  url: >-
    https://github.com/jesseduffield/lazydocker/releases/download/v{{ .lazydockerVersion }}/lazydocker_{{ .lazydockerVersion }}_Linux_x86_64.tar.gz
  executable: true
  filter:
    command: tar
    args:
      - "--extract"
      - "--file"
      - /dev/stdin
      - "--gzip"
      - "--to-stdout"
      - lazydocker

{{- if .isDesktop }}
.local/bin/neovide:
  type: file
  url: >-
    https://github.com/neovide/neovide/releases/download/{{ .neovideVersion }}/neovide.tar.gz
  executable: true
  filter:
    command: tar
    args:
      - "--extract"
      - "--file"
      - /dev/stdin
      - "--gzip"
      - "--to-stdout"
      - neovide
{{- end }}

.local/bin/rustfmt:
  type: file
  url: >-
    https://github.com/rust-lang/rustfmt/releases/download/v{{ .rustfmtVersion }}/rustfmt_{{ .chezmoi.os }}-x86_64_v{{ .rustfmtVersion }}.tar.gz
  executable: true
  filter:
    command: tar
    args:
      - "--extract"
      - "--file"
      - /dev/stdin
      - "--gzip"
      - "--to-stdout"
      - rustfmt_{{ .chezmoi.os }}-x86_64_v{{ .rustfmtVersion }}/rustfmt

.local/bin/starship:
  type: file
  url: >-
    https://github.com/starship/starship/releases/download/v{{ .starshipVersion }}/starship-x86_64-unknown-{{ .chezmoi.os }}-musl.tar.gz
  executable: true
  refreshPeriod: 168h
  filter:
    command: tar
    args:
      - "--extract"
      - "--file"
      - /dev/stdin
      - "--gzip"
      - "--to-stdout"
      - starship

.local/bin/taplo:
  type: file
  url: >-
    https://github.com/tamasfe/taplo/releases/download/0.8.0/taplo-full-linux-x86_64.gz
  executable: true
  filter:
    command: gzip
    args:
      - "-d"

.local/bin/tldr:
  type: file
  url: >-
    https://github.com/dbrgn/tealdeer/releases/download/v{{ .tealdeerVersion }}/tealdeer-{{ .chezmoi.os }}-x86_64-musl
  executable: true

.oh-my-zsh:
  type: git-repo
  url: "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod: 168h
  pull:
    args:
      - "--ff-only"

.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.oh-my-zsh/custom/plugins/zsh-autosuggestions:
  type: archive
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.oh-my-zsh/custom/plugins/zsh-completions:
  type: archive
  url: "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.tmux/plugins/tpm:
  type: git-repo
  url: "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod: 168h
  pull:
    args:
      - "--ff-only"

{{ end -}}
