# chezmoixternal -*- mode: tomal -*-
[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod = "168h"
  [".oh-my-zsh".pull]
    args = ["--ff-only"]
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-completions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/dhruvinsh/nvim.git"
  refreshPeriod = "168h"
  [".config/nvim".pull]
    args = ["--ff-only"]
{{ if eq .emacs true -}}
# emacs is set to true then we can think about adding doom setup else don't do it at all
{{ if eq .doom true -}}
# setup doom emacs if thats what we want
[".emacs.d"]
  type = "git-repo"
  url = "https://github.com/hlissner/doom-emacs.git"
  refreshPeriod = "168h"  # refresh after 7 days
  [".emacs.d".pull]
    args = ["--ff-only"]
# setup .doom.d folder as well
[".doom.d"]
  type = "git-repo"
  url = "https://github.com/dhruvinsh/doom.d"
  [".doom.d".pull]
    args = ["--ff-only"]
{{ end -}}
{{ if eq .purcell true -}}
# setup purcell (from fork) if thats what we want, I guess for now lets have habbit of this
[".emacs.d"]
  type = "git-repo"
  url = "https://github.com/dhruvinsh/purcell-emacs.d.git"
  refreshPeriod = "168h"  # refresh after 7 days
  [".emacs.d".pull]
    args = ["--ff-only"]
{{ end -}}
{{ end -}}
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod = "168h"
  [".tmux/plugins/tpm".pull]
    args = ["--ff-only"]
[".nvm"]
  type = "git-repo"
  url = "https://github.com/nvm-sh/nvm.git"
  refreshPeriod = "168h"
  [".nvm".pull]
    args = ["--ff-only"]
[".local/bin/syncthing"]
    type = "file"
    url = "https://github.com/syncthing/syncthing/releases/download/v{{ .syncthingVersion }}/syncthing-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-v{{ .syncthingVersion }}.tar.gz"
    executable = true
    [".local/bin/syncthing".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "syncthing-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-v{{ .syncthingVersion }}/syncthing"]
