# chezmoixternal -*- mode: toml -*-
# vim: set filetype=yaml

ageVersion: "1.0.0"
batVersion: "0.22.1"
emacsVersion: "28.2"
fdVersion: "8.4.0"
fzfVersion: "0.34.0"
ghVersion: "2.17.0"
goVersion: "1.19.2"
lazygitVersion: "0.35"
neovideVersion: "0.10.1"
neovimVersion: "0.8.0"
pythonVersion: "3.10.2"
ripgrepVersion: "13.0.0"
seleneVersion: "0.22.0"
shfmtVersion: "3.5.1"
styluaVersion: "0.15.1"
syncthingVersion: "1.22.0"
tealdeerVersion: "1.6.0"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion: "0.13.0"
