pythonVersion = "3.10.2"
goVersion = "1.17.8"
ripgrepVersion = "13.0.0"
fdVersion = "8.3.2"
fzfVersion = "0.29.0"
emacsVersion = "27.2"
ageVersion = "1.0.0"
styluaVersion = "0.13.1"
zenithVersion = "0.13.1"
