# chezmoixternal -*- mode: yaml -*-
# vim: set filetype=yaml

# prettier-ignore
ageVersion       : "1.1.1"
batVersion       : "0.23.0"
emacsVersion     : "28.2"
f3dVersion       : "2.0.0"
fdVersion        : "8.7.0"
freecadVersion   : "0.20.2-2022-12-27"
fzfVersion       : "0.40.0"
ghVersion        : "2.29.0"
goVersion        : "1.19.2"
lazydockerVersion: "0.20.0"
lazygitVersion   : "0.38.2"
logseqVersion    : "0.9.4"
neovideVersion   : "0.10.4"
neovimVersion    : "0.9.0"
nerdfontVersion  : "3.0.1"
nextcloudVersion : "3.8.1"
openscadVersion  : "2021.01"
pythonVersion    : "3.11.3"
ripgrepVersion   : "13.0.0"
rustfmtVersion   : "1.5.1"
sniffnetVersion  : "1.1.4"
starshipVersion  : "1.14.2"
syncthingVersion : "1.23.4"
tealdeerVersion  : "1.6.1"
weztermVersion   : "20230408-112425-69ae8472"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion    : "0.13.0"
