# chezmoixternal -*- mode: yaml -*-
# vim: set filetype=yaml

# prettier-ignore
ageVersion       : "1.1.1"
batVersion       : "0.23.0"
f3dVersion       : "2.0.0"
fdVersion        : "8.7.0"
freecadVersion   : "0.20.2-2022-12-27"
fzfVersion       : "0.41.1"
ghVersion        : "2.30.0"
helixVersion     : "23.05"
lazydockerVersion: "0.20.0"
lazygitVersion   : "0.38.2"
logseqVersion    : "0.9.8"
neovideVersion   : "0.10.4"
neovimVersion    : "0.9.1"
nerdfontVersion  : "3.0.2"
nextcloudVersion : "3.8.2"
openscadVersion  : "2021.01"
pythonVersion    : "3.11.4"
ripgrepVersion   : "13.0.0"
rustfmtVersion   : "1.5.1"
sniffnetVersion  : "1.2.0"
starshipVersion  : "1.15.0"
syncthingVersion : "1.23.4"
tealdeerVersion  : "1.6.1"
weztermVersion   : "20230408-112425-69ae8472"
zoxideVersion    : "0.9.1"
