# chezmoixternal -*- mode: toml -*-
# vim: set filetype=yaml

ageVersion: "1.1.1"
batVersion: "0.22.1"
emacsVersion: "28.2"
f3dVersion: "1.3.1"
fdVersion: "8.7.0"
freecadVersion: "0.20.2-2022-12-27"
fzfVersion: "0.38.0"
ghVersion: "2.23.0"
goVersion: "1.19.2"
lazygitVersion: "0.37.0"
logseqVersion: "0.8.17"
neovideVersion: "0.10.3"
neovimVersion: "0.8.3"
nextcloudVersion: "3.7.3"
openscadVersion: "2021.01"
pythonVersion: "3.11.2"
ripgrepVersion: "13.0.0"
rustfmtVersion: "1.5.1"
seleneVersion: "0.24.0"
shfmtVersion: "3.6.0"
starshipVersion: "1.13.1"
styluaVersion: "0.16.1"
syncthingVersion: "1.23.2"
tealdeerVersion: "1.6.1"
weztermVersion: "20221119-145034-49b9839f"
# eventhough zenit says v0.13.1 but actually it v0.13.0
zenithVersion: "0.13.0"
