[metadata]
name = "alacritty"
origin_url = "https://github.com/dhruvinsh/dotfiles"

[colors]
foreground = "#d8d8d8"
background = "#181818"

compose_cursor = "#75b5aa"
cursor_bg = "#d8d8d8"
cursor_fg = "#524f67"      # pending
cursor_border = "#d8d8d8"

selection_bg = "#d8d8d8" # pending
selection_fg = "#181818"

scrollbar_thumb = "#6b6b6b"
split = "#6b6b6b"
visual_bell = "#524f67"     # pending

ansi = [
  "#181818",
  "#ac4242",
  "#90a959",
  "#f4bf75",
  "#6a8fb5",
  "#aa759f",
  "#75b5aa",
  "#d8d8d8",
]
brights = [
  "#6b6b6b",
  "#c55555",
  "#aac574",
  "#feca88",
  "#82b8c8",
  "#c28cb8",
  "#93d3c3",
  "#f8f8f8",
]

[colors.indexed]

# this only applies to retro tab bar
# see: https://wezfurlong.org/wezterm/config/appearance.html
[colors.tab_bar]
background = "#181818" # tab bar and terminal background are same

[colors.tab_bar.active_tab]
bg_color = "#181818"
fg_color = "#d8d8d8"

[colors.tab_bar.inactive_tab]
bg_color = "#181818"
fg_color = "#6b6b6b"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#181818"
fg_color = "#d8d8d8"

[colors.tab_bar.new_tab]
bg_color = "#181818"
fg_color = "#6b6b6b"

# keep this colors similar to inactive_tab_hover
[colors.tab_bar.new_tab_hover]
bg_color = "#181818"
fg_color = "#d8d8d8"
